Authテーブルの処理。パスワードのハッシュ化。DBの接続。問題あり
docker:
$ docker-compose up -d で立ち上げて
$ mysql -u root -h 172.0.0.1 -p で接続

$ http -v post localhost:9000/v0/auths username=hogehoge@example.com password=password
とすると、
java.sql.SQLSyntaxErrorException: Table 'commenter.auths' doesn't exist
とあるので、DB初期化の処理がうまくいっていないようだ